<?php

namespace Tests\Feature;

use Tests\TestCase;

/**
 * Every class under `app/` can be declared.
 *
 * [#924](https://github.com/liberusoftware/ecommerce-laravel/issues/924) was
 * this failing on `User`: `Jetstream\HasTeams` and `Spatie\HasRoles` both
 * declare `teams()`, and PHP treats an unresolved trait collision as a **fatal
 * at class declaration**, not a warning at the call. The application did not
 * boot. Two traits landing on the same model is ordinary — the next pair is a
 * matter of time, and nothing in the suite noticed the first one.
 *
 * The same fatal has a second source, met while wiring `TrustHosts`: an
 * override that narrows a parameter type the parent left untyped. Also fatal at
 * declaration, also silent until something touches the class. In CI it surfaced
 * as `Premature end of PHP process` on whichever test happened to load it first,
 * which moves as the suite changes.
 *
 * A fatal cannot be caught, so it cannot be asserted in-process — the assertion
 * would die with the process it was making. The classes are declared in a
 * subprocess instead, each name printed *before* it is loaded, so the last line
 * of output names the class that killed it.
 */
class EveryClassLoadsTest extends TestCase
{
    public function test_every_class_under_app_can_be_declared(): void
    {
        $classes = $this->classes();

        $this->assertNotEmpty($classes, 'Found no classes under app/ — the path mapping is wrong.');

        $probe = tempnam(sys_get_temp_dir(), 'declare');

        file_put_contents($probe, $this->probe($classes));

        exec(implode(' ', [
            escapeshellarg(PHP_BINARY),
            '-d display_errors=1',
            '-d error_reporting=-1',
            escapeshellarg($probe),
            '2>&1',
        ]), $output, $status);

        @unlink($probe);

        $this->assertSame(0, $status, implode("\n", [
            'A class under app/ cannot be declared. Whatever loads it first dies with it,',
            'so this is a boot failure rather than a test failure — see #924.',
            '',
            'Each name is printed before it is loaded, so the tail below ends on the',
            'class that killed the process, followed by whatever PHP managed to say:',
            '',
            '  '.implode("\n  ", array_slice($output, -5) ?: ['(no output — the probe never started)']),
            '',
            'Two things produce this fatal: two traits declaring the same method with',
            'no `insteadof`, and an override that narrows a parameter the parent left',
            'untyped.',
        ]));
    }

    /**
     * Declaring a class is the whole test — a `Throwable` is swallowed because
     * it is not the failure being looked for. A missing parent class raises a
     * catchable `Error`, which is a broken reference; a trait collision raises a
     * fatal, which is a broken deployment.
     *
     * @param  list<class-string>  $classes
     */
    private function probe(array $classes): string
    {
        return implode("\n", [
            '<?php',
            'require '.var_export(base_path('vendor/autoload.php'), true).';',
            'foreach ('.var_export($classes, true).' as $name) {',
            '    echo $name, PHP_EOL;',
            '    try {',
            '        class_exists($name) || interface_exists($name) || trait_exists($name) || enum_exists($name);',
            '    } catch (Throwable) {',
            '    }',
            '}',
            '',
        ]);
    }

    /**
     * Every PHP file under `app/`, as the class name PSR-4 would give it.
     *
     * Read from the filesystem rather than from Composer's classmap, because an
     * optimised classmap is generated by a command that has to load nothing —
     * a class it could not declare would still be listed there.
     *
     * @return list<class-string>
     */
    private function classes(): array
    {
        $classes = [];
        $root = app_path();

        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS),
        );

        foreach ($files as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }

            $relative = substr($file->getPathname(), strlen($root) + 1, -strlen('.php'));

            $classes[] = 'App\\'.str_replace(DIRECTORY_SEPARATOR, '\\', $relative);
        }

        sort($classes);

        return $classes;
    }
}
